# Generated by Django 4.0.3 on 2022-03-22 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
    ]
