# Generated by Django 4.0.3 on 2022-03-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='sulg',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
