# Generated by Django 4.0.3 on 2022-03-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
