# Generated by Django 4.0.3 on 2022-03-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_apply_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='cv',
            field=models.FileField(upload_to='apply/'),
        ),
    ]
